# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Aashvi Care' do
  use_frameworks!

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  # Networking - JSON Parsing
  pod 'SwiftyJSON'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'RxSwift'
  
  # Async Display Kit
  pod 'Texture/IGListKit'
  
  # Graphs
  pod 'Charts', '3.3.0'
end

target 'Aashvi CareTests' do
  inherit! :search_paths
  pod 'Quick', '~> 2.1.0'
  pod 'Nimble', '~> 8.0.1'
  pod 'OHHTTPStubs/Swift'
  pod 'EarlGrey'
  
  pod 'Firebase'
end

target 'Aashvi CareUITests' do
  inherit! :search_paths
end

