# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Aashvi Care' do
  use_frameworks!

  # Pods for Aashvi Care
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  pod 'SwiftyJSON'
  pod 'RxSwift'
  
  target 'Aashvi CareUITests' do
    inherit! :search_paths
  end

end

target 'Aashvi CareTests' do
  inherit! :search_paths
  pod 'Quick', '~> 2.1.0'
  pod 'Nimble', '~> 8.0.1'
  
  pod 'Firebase'
end
